--CREATE TABLE CUSTOMER 
CREATE TABLE CUSTOMER 
(
CUST_ID NUMBER PRIMARY KEY,

NAME VARCHAR (100),
PASSWORD VARCHAR(50)
)
COMMIT;

CREATE TABLE EMPLOYEE
(
EMPLOYEE_ID NUMBER PRIMARY KEY,
NAME VARCHAR (100),
PASSWORD VARCHAR(50)
)
COMMIT;

CREATE TABLE ADMIN
(
ADMIN_ID NUMBER PRIMARY KEY,
NAME VARCHAR (100),
PASSWORD VARCHAR (50)
);

CREATE TABLE ACCOUNTS
(
ACCOUNT_NUMBER NUMBER PRIMARY KEY,
APPROVED CHAR(1),
BALANCE NUMBER (22,2)CHECK (BALANCE >0)
);

CREATE TABLE CUSTOMER_ACCOUNTS
(
CUST_ID NUMBER,
ACCOUNT_NUMBER NUMBER
);

COMMIT;

ALTER TABLE CUSTOMER 
ADD USERID VARCHAR (50);

CREATE SEQUENCE CUST_ID_SEQ MINVALUE 1 INCREMENT BY 1 CACHE 50;

CREATE OR REPLACE TRIGGER CUST_TRIGG
BEFORE INSERT ON CUSTOMER
FOR EACH ROW
--COULD DECLARE
BEGIN
    SELECT CUST_ID_SEQ.NEXTVAL INTO :new.CUST_ID FROM DUAL;
END; 

